# 服务器配置
server:
  port: 8080

spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  mvc:
    view:
      suffix: .html
      prefix: /
  #    文件上传大小限制
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB




# MyBatis配置

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tour.model
  configuration:
    map-underscore-to-camel-case: true

# 日志配置
logging:
  level:
    root: info
    com.tour: debug
    org.springframework.web: debug
    org.springframework.security: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'


jwt:
  secret: your_jwt_secret_key  # 建议使用Base64编码的字符串
  expiration: 86400000         # token过期时间(毫秒)

# 安全配置
security:
  # 白名单路径，无需认证即可访问
  whiteList:
    - /api/auth/**        # 认证接口
    - /api/articles       # 获取文章列表
    - /api/articles/*     # 获取文章详情
    - /api/profile        # 获取个人资料
    - /error              # 错误页面
    - /doc.html   # 接口文档
    - /doc.html/**   # 接口文档
    - /swagger-resources
    - /v2/api-docs
  # 管理员路径，需要管理员权限
  adminUrls:
    - /api/admin/**       # 管理员接口

my:
  minio:
    access-key: 7f1qYrlpzVBmuFuE5WJP
    secret-key: nVUTh5AKJ533yBfkz9esX8Mgbg65LpEyBWTqHlaV
    ip_addr: https://www.kuril.site:9000
    bucketName: public
    filePath: /avatar