# 服务器配置
server:
  port: 80
  tomcat:
    max-threads: 300
    min-spare-threads: 30
    max-connections: 10000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true

# 安全配置
security:
  white-list:
    urls:
      - /api/auth/wxLogin
      - /api/auth/check
      - /api/common/**
      - /error
      - /api/count
      - /api/wx/message/receive
      - /api/wx/payment/notify/**
      - /api/wx/payment/cloud/refund/notify
      - /api/wx/payment/cloud/**

spring:
  application:
    name: tour
  # 数据库配置 - 使用微信云托管的MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 微信云托管会自动注入以下环境变量
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:tour}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ${MYSQL_USERNAME}  # 由微信云托管自动注入
    password: ${MYSQL_PASSWORD}  # 由微信云托管自动注入
  mvc:
    view:
      suffix: .html
      prefix: /
    pathmatch:
      matching-strategy: ant_path_matcher
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT加解密使用的密钥(64字节以上)
  secret: ${JWT_SECRET:prod_jwt_secret_key_123456}
  # JWT的超期限时间(单位毫秒)
  expiration: ${JWT_EXPIRATION:2592000000}
  # JWT负载中拿到开头
  tokenHead: Bearer

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tour.model
  configuration:
    map-underscore-to-camel-case: true

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    root: warn
    com.tour: info
  file:
    name: /data/logs/tour.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30


